//! Minimal hand-rolled Apache Thrift `TBinaryProtocol` -- just enough wire
//! format to speak Databricks' HiveServer2-compatible TCLIService (the same
//! legacy, binary-encoded-over-plain-HTTPS protocol `databricks-sql-connector`
//! speaks by *default* when `use_sea` isn't set, and measurably faster than
//! this crate's own SEA/REST path for small queries -- see the `protocol`
//! opt-in on `Client`/`DatabricksClient`). Deliberately not a general Thrift
//! implementation and not the full ~22-RPC TCLIService surface: this crate
//! has zero catalog/table/column-browsing API surface (no GetCatalogs/
//! GetSchemas/GetTables/GetColumns/etc.), so only the 7 RPCs it actually
//! needs are implemented: `OpenSession`, `ExecuteStatement`,
//! `GetOperationStatus`, `FetchResults`, `CloseOperation`, `CloseSession`,
//! `CancelOperation`.
//!
//! Every struct's field IDs/types below were read directly out of
//! `databricks-sql-connector`'s own installed `thrift_api/TCLIService/ttypes.py`
//! (generated by the real Apache Thrift compiler from Databricks' actual
//! `.thrift` IDL, so it's the ground truth for the wire format) rather than
//! guessed at or taken from public Hive/Thrift documentation, which doesn't
//! cover Databricks' own extension fields (the ones with IDs >= 1281 --
//! Databricks reserves that range for its own additions on top of stock
//! Hive's TCLIService).
//!
//! A hand-rolled reader/writer was chosen over pulling in the `thrift` crate
//! from crates.io: the actual wire format needed here (`TBinaryProtocol`,
//! plain big-endian ints/strings/structs, no compact-protocol varints) is a
//! few hundred lines of straight-line code, and hand-writing it keeps this
//! crate's "no new Cargo dependency without checking whether existing code
//! can do it instead" bar (see `AGENTS.md`'s Dependencies section) clean of a
//! whole generic RPC framework for 7 RPCs' worth of concrete structs.

use bytes::Bytes;

// ---- Wire-level type tags (`TType` in Thrift's own terminology) ----------

pub mod ttype {
    pub const STOP: i8 = 0;
    pub const BOOL: i8 = 2;
    pub const BYTE: i8 = 3;
    pub const DOUBLE: i8 = 4;
    pub const I16: i8 = 6;
    pub const I32: i8 = 8;
    pub const I64: i8 = 10;
    pub const STRING: i8 = 11;
    pub const STRUCT: i8 = 12;
    pub const MAP: i8 = 13;
    pub const SET: i8 = 14;
    pub const LIST: i8 = 15;
}

pub const MESSAGE_TYPE_CALL: i32 = 1;
pub const MESSAGE_TYPE_EXCEPTION: i32 = 3;
/// `0x80010000` as a signed i32 -- `TBinaryProtocol`'s own "strict write"
/// version marker, OR'd with the message type. Confirmed against
/// `thrift`'s own `TBinaryProtocol.VERSION_1 = -2147418112` (its comment:
/// "Python 2.4+ on 32-bit machines forces hex constants to be positive... if
/// we hardcode the int value instead it'll stay in 32-bit land" -- same
/// reasoning applies here, spelled out as a plain i32 rather than a hex
/// literal that could get reinterpreted).
const VERSION_1: i32 = -2147418112;

/// Databricks-specific protocol version enum value (not a stock Hive one) --
/// `databricks-sql-connector` always sends this on `TOpenSessionReq.client_protocol_i64`.
pub const SPARK_CLI_SERVICE_PROTOCOL_V7: i64 = 42247;

// ---- Writer ---------------------------------------------------------------

#[derive(Default)]
pub struct Writer {
    buf: Vec<u8>,
}

impl Writer {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn into_bytes(self) -> Vec<u8> {
        self.buf
    }

    pub fn write_message_begin(&mut self, name: &str, msg_type: i32, seqid: i32) {
        self.write_i32(VERSION_1 | msg_type);
        self.write_string(name);
        self.write_i32(seqid);
    }

    pub fn write_field_begin(&mut self, ttype: i8, id: i16) {
        self.write_i8(ttype);
        self.write_i16(id);
    }

    pub fn write_field_stop(&mut self) {
        self.write_i8(ttype::STOP);
    }

    pub fn write_list_begin(&mut self, elem_type: i8, size: i32) {
        self.write_i8(elem_type);
        self.write_i32(size);
    }

    pub fn write_map_begin(&mut self, ktype: i8, vtype: i8, size: i32) {
        self.write_i8(ktype);
        self.write_i8(vtype);
        self.write_i32(size);
    }

    pub fn write_i8(&mut self, v: i8) {
        self.buf.push(v as u8);
    }
    pub fn write_i16(&mut self, v: i16) {
        self.buf.extend_from_slice(&v.to_be_bytes());
    }
    pub fn write_i32(&mut self, v: i32) {
        self.buf.extend_from_slice(&v.to_be_bytes());
    }
    pub fn write_i64(&mut self, v: i64) {
        self.buf.extend_from_slice(&v.to_be_bytes());
    }
    pub fn write_double(&mut self, v: f64) {
        self.buf.extend_from_slice(&v.to_be_bytes());
    }
    pub fn write_bool(&mut self, v: bool) {
        self.write_i8(v as i8);
    }
    pub fn write_binary(&mut self, v: &[u8]) {
        self.write_i32(v.len() as i32);
        self.buf.extend_from_slice(v);
    }
    pub fn write_string(&mut self, v: &str) {
        self.write_binary(v.as_bytes());
    }
}

// ---- Reader -----------------------------------------------------------

#[derive(Debug)]
pub struct ThriftError(pub String);

impl std::fmt::Display for ThriftError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}
impl std::error::Error for ThriftError {}

type TResult<T> = Result<T, ThriftError>;

pub struct Reader<'a> {
    buf: &'a [u8],
    pos: usize,
}

impl<'a> Reader<'a> {
    pub fn new(buf: &'a [u8]) -> Self {
        Self { buf, pos: 0 }
    }

    fn take(&mut self, n: usize) -> TResult<&'a [u8]> {
        if self.pos + n > self.buf.len() {
            return Err(ThriftError(format!(
                "unexpected end of thrift message (need {n} bytes, have {})",
                self.buf.len() - self.pos
            )));
        }
        let s = &self.buf[self.pos..self.pos + n];
        self.pos += n;
        Ok(s)
    }

    pub fn read_i8(&mut self) -> TResult<i8> {
        Ok(self.take(1)?[0] as i8)
    }
    pub fn read_i16(&mut self) -> TResult<i16> {
        Ok(i16::from_be_bytes(self.take(2)?.try_into().unwrap()))
    }
    pub fn read_i32(&mut self) -> TResult<i32> {
        Ok(i32::from_be_bytes(self.take(4)?.try_into().unwrap()))
    }
    pub fn read_i64(&mut self) -> TResult<i64> {
        Ok(i64::from_be_bytes(self.take(8)?.try_into().unwrap()))
    }
    pub fn read_double(&mut self) -> TResult<f64> {
        Ok(f64::from_be_bytes(self.take(8)?.try_into().unwrap()))
    }
    pub fn read_bool(&mut self) -> TResult<bool> {
        Ok(self.read_i8()? != 0)
    }
    pub fn read_binary(&mut self) -> TResult<Bytes> {
        let len = self.read_i32()?;
        if len < 0 {
            return Err(ThriftError("negative binary length in thrift message".into()));
        }
        Ok(Bytes::copy_from_slice(self.take(len as usize)?))
    }
    pub fn read_string(&mut self) -> TResult<String> {
        let b = self.read_binary()?;
        String::from_utf8(b.to_vec()).map_err(|e| ThriftError(format!("bad utf8 in thrift string: {e}")))
    }

    /// Returns `(name, message_type, seqid)`. Only the "strict" (version-
    /// prefixed, negative-leading-i32) framing is handled beyond a minimal
    /// fallback -- Databricks' own server always writes strict messages
    /// (confirmed: `THttpClient`/`TBinaryProtocol` default to `strictWrite=True`),
    /// the non-strict branch here is just defensive, not exercised in practice.
    pub fn read_message_begin(&mut self) -> TResult<(String, i32, i32)> {
        let sz = self.read_i32()?;
        if sz < 0 {
            let msg_type = sz & 0x0000_00ff;
            let name = self.read_string()?;
            let seqid = self.read_i32()?;
            Ok((name, msg_type, seqid))
        } else {
            let name = String::from_utf8_lossy(self.take(sz as usize)?).to_string();
            let msg_type = self.read_i8()? as i32;
            let seqid = self.read_i32()?;
            Ok((name, msg_type, seqid))
        }
    }

    /// `(field_type, field_id)` -- `field_id` is meaningless (0) when
    /// `field_type == ttype::STOP`, matching every field-id-less STOP marker
    /// in the wire format.
    pub fn read_field_begin(&mut self) -> TResult<(i8, i16)> {
        let ftype = self.read_i8()?;
        if ftype == ttype::STOP {
            return Ok((ttype::STOP, 0));
        }
        let id = self.read_i16()?;
        Ok((ftype, id))
    }

    pub fn read_list_begin(&mut self) -> TResult<(i8, i32)> {
        let etype = self.read_i8()?;
        let size = self.read_i32()?;
        Ok((etype, size))
    }

    pub fn read_map_begin(&mut self) -> TResult<(i8, i8, i32)> {
        let kt = self.read_i8()?;
        let vt = self.read_i8()?;
        let size = self.read_i32()?;
        Ok((kt, vt, size))
    }

    /// Skips one value of `ftype`, recursing into structs/lists/maps/sets.
    /// Needed so every field this crate doesn't care about (the majority of
    /// every response struct read here -- e.g. `TStatus.infoMessages`,
    /// `TGetOperationStatusResp.progressUpdateResponse`) can be skipped
    /// generically instead of requiring a hand-written no-op parser for
    /// each one. This is Thrift's own designed-in forward-compatibility
    /// mechanism (every field is self-describing on the wire, type + id),
    /// not a workaround.
    pub fn skip(&mut self, ftype: i8) -> TResult<()> {
        match ftype {
            ttype::BOOL | ttype::BYTE => {
                self.read_i8()?;
            }
            ttype::I16 => {
                self.read_i16()?;
            }
            ttype::I32 => {
                self.read_i32()?;
            }
            ttype::I64 => {
                self.read_i64()?;
            }
            ttype::DOUBLE => {
                self.read_double()?;
            }
            ttype::STRING => {
                self.read_binary()?;
            }
            ttype::STRUCT => loop {
                let (ft, _id) = self.read_field_begin()?;
                if ft == ttype::STOP {
                    break;
                }
                self.skip(ft)?;
            },
            ttype::LIST | ttype::SET => {
                let (et, size) = self.read_list_begin()?;
                for _ in 0..size {
                    self.skip(et)?;
                }
            }
            ttype::MAP => {
                let (kt, vt, size) = self.read_map_begin()?;
                for _ in 0..size {
                    self.skip(kt)?;
                    self.skip(vt)?;
                }
            }
            other => return Err(ThriftError(format!("cannot skip unknown thrift type tag {other}"))),
        }
        Ok(())
    }
}

// ---- Handles ------------------------------------------------------------

#[derive(Debug, Clone)]
pub struct HandleId {
    pub guid: Bytes,
    pub secret: Bytes,
}

impl HandleId {
    fn read(r: &mut Reader) -> TResult<Self> {
        let mut guid = None;
        let mut secret = None;
        loop {
            let (ft, id) = r.read_field_begin()?;
            if ft == ttype::STOP {
                break;
            }
            match (id, ft) {
                (1, ttype::STRING) => guid = Some(r.read_binary()?),
                (2, ttype::STRING) => secret = Some(r.read_binary()?),
                (_, ft) => r.skip(ft)?,
            }
        }
        Ok(Self {
            guid: guid.ok_or_else(|| ThriftError("THandleIdentifier missing guid".into()))?,
            secret: secret.ok_or_else(|| ThriftError("THandleIdentifier missing secret".into()))?,
        })
    }

    fn write(&self, w: &mut Writer) {
        w.write_field_begin(ttype::STRING, 1);
        w.write_binary(&self.guid);
        w.write_field_begin(ttype::STRING, 2);
        w.write_binary(&self.secret);
        w.write_field_stop();
    }
}

#[derive(Debug, Clone)]
pub struct SessionHandle {
    pub session_id: HandleId,
}

impl SessionHandle {
    fn read(r: &mut Reader) -> TResult<Self> {
        let mut session_id = None;
        loop {
            let (ft, id) = r.read_field_begin()?;
            if ft == ttype::STOP {
                break;
            }
            match (id, ft) {
                (1, ttype::STRUCT) => session_id = Some(HandleId::read(r)?),
                (_, ft) => r.skip(ft)?,
            }
        }
        Ok(Self {
            session_id: session_id.ok_or_else(|| ThriftError("TSessionHandle missing sessionId".into()))?,
        })
    }

    fn write(&self, w: &mut Writer) {
        w.write_field_begin(ttype::STRUCT, 1);
        self.session_id.write(w);
        w.write_field_stop();
    }
}

#[derive(Debug, Clone)]
pub struct OperationHandle {
    pub operation_id: HandleId,
    pub operation_type: i32,
    pub has_result_set: bool,
    pub modified_row_count: Option<f64>,
}

impl OperationHandle {
    fn read(r: &mut Reader) -> TResult<Self> {
        let mut operation_id = None;
        let mut operation_type = None;
        let mut has_result_set = None;
        let mut modified_row_count = None;
        loop {
            let (ft, id) = r.read_field_begin()?;
            if ft == ttype::STOP {
                break;
            }
            match (id, ft) {
                (1, ttype::STRUCT) => operation_id = Some(HandleId::read(r)?),
                (2, ttype::I32) => operation_type = Some(r.read_i32()?),
                (3, ttype::BOOL) => has_result_set = Some(r.read_bool()?),
                (4, ttype::DOUBLE) => modified_row_count = Some(r.read_double()?),
                (_, ft) => r.skip(ft)?,
            }
        }
        Ok(Self {
            operation_id: operation_id.ok_or_else(|| ThriftError("TOperationHandle missing operationId".into()))?,
            operation_type: operation_type
                .ok_or_else(|| ThriftError("TOperationHandle missing operationType".into()))?,
            has_result_set: has_result_set
                .ok_or_else(|| ThriftError("TOperationHandle missing hasResultSet".into()))?,
            modified_row_count,
        })
    }

    fn write(&self, w: &mut Writer) {
        w.write_field_begin(ttype::STRUCT, 1);
        self.operation_id.write(w);
        w.write_field_begin(ttype::I32, 2);
        w.write_i32(self.operation_type);
        w.write_field_begin(ttype::BOOL, 3);
        w.write_bool(self.has_result_set);
        if let Some(m) = self.modified_row_count {
            w.write_field_begin(ttype::DOUBLE, 4);
            w.write_double(m);
        }
        w.write_field_stop();
    }
}

// ---- TStatus / errors ----------------------------------------------------

pub mod status_code {
    pub const SUCCESS: i32 = 0;
    pub const SUCCESS_WITH_INFO: i32 = 1;
    pub const STILL_EXECUTING: i32 = 2;
    pub const ERROR: i32 = 3;
    pub const INVALID_HANDLE: i32 = 4;
}

pub mod operation_state {
    pub const INITIALIZED: i32 = 0;
    pub const RUNNING: i32 = 1;
    pub const FINISHED: i32 = 2;
    pub const CANCELED: i32 = 3;
    pub const CLOSED: i32 = 4;
    pub const ERROR: i32 = 5;
    pub const PENDING: i32 = 7;
    pub const TIMEDOUT: i32 = 8;
}

#[derive(Debug, Default)]
pub struct Status {
    pub status_code: i32,
    pub error_message: Option<String>,
    pub display_message: Option<String>,
}

impl Status {
    fn read(r: &mut Reader) -> TResult<Self> {
        let mut out = Status {
            status_code: status_code::SUCCESS,
            error_message: None,
            display_message: None,
        };
        loop {
            let (ft, id) = r.read_field_begin()?;
            if ft == ttype::STOP {
                break;
            }
            match (id, ft) {
                (1, ttype::I32) => out.status_code = r.read_i32()?,
                (5, ttype::STRING) => out.error_message = Some(r.read_string()?),
                (6, ttype::STRING) => out.display_message = Some(r.read_string()?),
                (_, ft) => r.skip(ft)?,
            }
        }
        Ok(out)
    }

    /// `None` if this status doesn't represent a failure -- `SUCCESS`/
    /// `SUCCESS_WITH_INFO` are the only non-error codes; `STILL_EXECUTING`
    /// only ever appears on an async poll response, never on a call this
    /// crate treats as terminal.
    pub fn error(&self) -> Option<String> {
        if matches!(self.status_code, status_code::SUCCESS | status_code::SUCCESS_WITH_INFO) {
            return None;
        }
        Some(
            self.display_message
                .clone()
                .or_else(|| self.error_message.clone())
                .unwrap_or_else(|| format!("thrift status code {}", self.status_code)),
        )
    }
}

/// A `TMessageType::EXCEPTION` reply -- a protocol-level application
/// exception (bad method name, wrong sequence id, ...), distinct from a
/// normal result struct whose own `TStatus` says `ERROR_STATUS`.
fn read_application_exception(r: &mut Reader) -> TResult<String> {
    let mut message = None;
    loop {
        let (ft, id) = r.read_field_begin()?;
        if ft == ttype::STOP {
            break;
        }
        match (id, ft) {
            (1, ttype::STRING) => message = Some(r.read_string()?),
            (_, ft) => r.skip(ft)?,
        }
    }
    Ok(message.unwrap_or_else(|| "thrift application exception (no message)".to_string()))
}

// ---- TNamespace / TSparkArrowTypes / TSparkParameter (write-only) --------

pub struct Namespace<'a> {
    pub catalog_name: Option<&'a str>,
    pub schema_name: Option<&'a str>,
}

impl Namespace<'_> {
    fn write(&self, w: &mut Writer) {
        if let Some(c) = self.catalog_name {
            w.write_field_begin(ttype::STRING, 1);
            w.write_string(c);
        }
        if let Some(s) = self.schema_name {
            w.write_field_begin(ttype::STRING, 2);
            w.write_string(s);
        }
        w.write_field_stop();
    }
}

/// Which native-Arrow-typed representations to ask the server for instead of
/// its own string/JSON fallback encodings -- mirrors
/// `databricks-sql-connector`'s own defaults. `interval_types_as_arrow` stays
/// `false` even though everything else is `true`: the connector's own
/// comment notes the interval Arrow type it would produce
/// (`month_day_nano_interval`) isn't something its Arrow reader (pyarrow)
/// can deserialize either, i.e. this is a known, shared limitation, not
/// something specific to this crate.
struct SparkArrowTypes {
    timestamp_as_arrow: bool,
    decimal_as_arrow: bool,
    complex_types_as_arrow: bool,
    interval_types_as_arrow: bool,
    null_type_as_arrow: bool,
}

impl SparkArrowTypes {
    fn write(&self, w: &mut Writer) {
        w.write_field_begin(ttype::BOOL, 1);
        w.write_bool(self.timestamp_as_arrow);
        w.write_field_begin(ttype::BOOL, 2);
        w.write_bool(self.decimal_as_arrow);
        w.write_field_begin(ttype::BOOL, 3);
        w.write_bool(self.complex_types_as_arrow);
        w.write_field_begin(ttype::BOOL, 4);
        w.write_bool(self.interval_types_as_arrow);
        w.write_field_begin(ttype::BOOL, 5);
        w.write_bool(self.null_type_as_arrow);
        w.write_field_stop();
    }
}

/// One bound named parameter -- mirrors this crate's existing SEA
/// `parameters` contract (`[{"name":..., "value":..., "type":...}]`, bound
/// against `:name` markers in the statement), converted here into
/// `TSparkParameter`'s shape (`value` as a `TSparkParameterValue.stringValue`
/// regardless of the parameter's real type, same as SEA's own JSON contract
/// -- the server parses the string per the accompanying `type` field either
/// way).
pub struct SparkParameter {
    pub name: String,
    pub sql_type: Option<String>,
    pub value: Option<String>,
}

impl SparkParameter {
    fn write(&self, w: &mut Writer) {
        w.write_field_begin(ttype::STRING, 2);
        w.write_string(&self.name);
        if let Some(t) = &self.sql_type {
            w.write_field_begin(ttype::STRING, 3);
            w.write_string(t);
        }
        if let Some(v) = &self.value {
            w.write_field_begin(ttype::STRUCT, 4);
            // TSparkParameterValue { stringValue = 1 }
            w.write_field_begin(ttype::STRING, 1);
            w.write_string(v);
            w.write_field_stop();
        }
        w.write_field_stop();
    }
}

/// Converts this crate's existing SEA-shaped `parameters` JSON
/// (`[{"name": ..., "value": ..., "type": ...}]`) into `TSparkParameter`s --
/// same "no validation of the caller's shape" contract as the SEA path
/// (`client.rs`'s `execute_statement` passes `parameters` straight through
/// to the request body too).
pub fn parameters_from_json(value: &serde_json::Value) -> Vec<SparkParameter> {
    let Some(arr) = value.as_array() else { return Vec::new() };
    arr.iter()
        .filter_map(|item| {
            let obj = item.as_object()?;
            let name = obj.get("name")?.as_str()?.to_string();
            let sql_type = obj.get("type").and_then(|v| v.as_str()).map(str::to_string);
            let value = obj.get("value").map(|v| match v {
                serde_json::Value::String(s) => s.clone(),
                serde_json::Value::Null => String::new(),
                other => other.to_string(),
            });
            Some(SparkParameter { name, sql_type, value })
        })
        .collect()
}

// ---- Requests (write-only) ------------------------------------------------

pub struct OpenSessionReq<'a> {
    pub namespace: Option<Namespace<'a>>,
    pub configuration: &'a [(&'a str, &'a str)],
}

impl OpenSessionReq<'_> {
    pub fn write(&self, w: &mut Writer) {
        // client_protocol (fid 1) intentionally omitted -- databricks-sql-connector
        // sends `client_protocol=None` too once `client_protocol_i64` (its
        // Databricks-specific replacement) is set.
        if !self.configuration.is_empty() {
            w.write_field_begin(ttype::MAP, 4);
            w.write_map_begin(ttype::STRING, ttype::STRING, self.configuration.len() as i32);
            for (k, v) in self.configuration {
                w.write_string(k);
                w.write_string(v);
            }
        }
        w.write_field_begin(ttype::I64, 1282); // client_protocol_i64
        w.write_i64(SPARK_CLI_SERVICE_PROTOCOL_V7);
        if let Some(ns) = &self.namespace {
            w.write_field_begin(ttype::STRUCT, 1284); // initialNamespace
            ns.write(w);
        }
        w.write_field_begin(ttype::BOOL, 1285); // canUseMultipleCatalogs
        w.write_bool(true);
        w.write_field_stop();
    }
}

pub struct OpenSessionResp {
    pub status: Status,
    pub session_handle: Option<SessionHandle>,
}

impl OpenSessionResp {
    fn read(r: &mut Reader) -> TResult<Self> {
        let mut status = None;
        let mut session_handle = None;
        loop {
            let (ft, id) = r.read_field_begin()?;
            if ft == ttype::STOP {
                break;
            }
            match (id, ft) {
                (1, ttype::STRUCT) => status = Some(Status::read(r)?),
                (3, ttype::STRUCT) => session_handle = Some(SessionHandle::read(r)?),
                (_, ft) => r.skip(ft)?,
            }
        }
        Ok(Self {
            status: status.ok_or_else(|| ThriftError("TOpenSessionResp missing status".into()))?,
            session_handle,
        })
    }
}

pub struct ExecuteStatementReq<'a> {
    pub session_handle: &'a SessionHandle,
    pub statement: &'a str,
    pub can_decompress_lz4: bool,
    pub direct_results_max_rows: i64,
    pub direct_results_max_bytes: i64,
    pub parameters: &'a [SparkParameter],
}

impl ExecuteStatementReq<'_> {
    pub fn write(&self, w: &mut Writer) {
        w.write_field_begin(ttype::STRUCT, 1);
        self.session_handle.write(w);
        w.write_field_begin(ttype::STRING, 2);
        w.write_string(self.statement);
        // confOverlay: force real Arrow timestamps for this statement too
        // (also set at session level, but cheap/harmless to repeat -- mirrors
        // databricks-sql-connector's own `merged_conf_overlay`).
        w.write_field_begin(ttype::MAP, 3);
        w.write_map_begin(ttype::STRING, ttype::STRING, 1);
        w.write_string("spark.thriftserver.arrowBasedRowSet.timestampAsString");
        w.write_string("false");
        w.write_field_begin(ttype::BOOL, 4); // runAsync
        w.write_bool(true);
        w.write_field_begin(ttype::STRUCT, 1281); // getDirectResults
        w.write_field_begin(ttype::I64, 1);
        w.write_i64(self.direct_results_max_rows);
        w.write_field_begin(ttype::I64, 2);
        w.write_i64(self.direct_results_max_bytes);
        w.write_field_stop();
        w.write_field_begin(ttype::BOOL, 1282); // canReadArrowResult
        w.write_bool(true);
        w.write_field_begin(ttype::BOOL, 1283); // canDownloadResult (cloud fetch)
        w.write_bool(true);
        w.write_field_begin(ttype::BOOL, 1284); // canDecompressLZ4Result
        w.write_bool(self.can_decompress_lz4);
        w.write_field_begin(ttype::STRUCT, 1286); // useArrowNativeTypes
        SparkArrowTypes {
            timestamp_as_arrow: true,
            decimal_as_arrow: true,
            complex_types_as_arrow: true,
            interval_types_as_arrow: false,
            null_type_as_arrow: true,
        }
        .write(w);
        if !self.parameters.is_empty() {
            w.write_field_begin(ttype::LIST, 1288);
            w.write_list_begin(ttype::STRUCT, self.parameters.len() as i32);
            for p in self.parameters {
                p.write(w);
            }
        }
        w.write_field_stop();
    }
}

#[derive(Debug, Clone)]
pub struct ArrowBatch {
    pub batch: Bytes,
    pub row_count: i64,
}

#[derive(Debug, Clone)]
pub struct ResultLink {
    pub file_link: String,
    pub row_count: i64,
}

#[derive(Debug, Default)]
pub struct RowSet {
    pub arrow_batches: Vec<ArrowBatch>,
    pub result_links: Vec<ResultLink>,
}

impl RowSet {
    fn read(r: &mut Reader) -> TResult<Self> {
        let mut out = RowSet::default();
        loop {
            let (ft, id) = r.read_field_begin()?;
            if ft == ttype::STOP {
                break;
            }
            match (id, ft) {
                (1281, ttype::LIST) => {
                    let (_et, size) = r.read_list_begin()?;
                    for _ in 0..size {
                        out.arrow_batches.push(read_arrow_batch(r)?);
                    }
                }
                (1282, ttype::LIST) => {
                    let (_et, size) = r.read_list_begin()?;
                    for _ in 0..size {
                        out.result_links.push(read_result_link(r)?);
                    }
                }
                (_, ft) => r.skip(ft)?,
            }
        }
        Ok(out)
    }
}

fn read_arrow_batch(r: &mut Reader) -> TResult<ArrowBatch> {
    let mut batch = None;
    let mut row_count = None;
    loop {
        let (ft, id) = r.read_field_begin()?;
        if ft == ttype::STOP {
            break;
        }
        match (id, ft) {
            (1, ttype::STRING) => batch = Some(r.read_binary()?),
            (2, ttype::I64) => row_count = Some(r.read_i64()?),
            (_, ft) => r.skip(ft)?,
        }
    }
    Ok(ArrowBatch {
        batch: batch.ok_or_else(|| ThriftError("TSparkArrowBatch missing batch".into()))?,
        row_count: row_count.unwrap_or(0),
    })
}

fn read_result_link(r: &mut Reader) -> TResult<ResultLink> {
    let mut file_link = None;
    let mut row_count = 0i64;
    loop {
        let (ft, id) = r.read_field_begin()?;
        if ft == ttype::STOP {
            break;
        }
        match (id, ft) {
            (1, ttype::STRING) => file_link = Some(r.read_string()?),
            (4, ttype::I64) => row_count = r.read_i64()?,
            (_, ft) => r.skip(ft)?,
        }
    }
    Ok(ResultLink {
        file_link: file_link.ok_or_else(|| ThriftError("TSparkArrowResultLink missing fileLink".into()))?,
        row_count,
    })
}

#[derive(Debug, Default)]
pub struct ResultSetMetadata {
    pub lz4_compressed: bool,
    pub arrow_schema: Option<Bytes>,
}

impl ResultSetMetadata {
    fn read(r: &mut Reader) -> TResult<Self> {
        let mut out = ResultSetMetadata::default();
        loop {
            let (ft, id) = r.read_field_begin()?;
            if ft == ttype::STOP {
                break;
            }
            match (id, ft) {
                (1282, ttype::BOOL) => out.lz4_compressed = r.read_bool()?,
                (1283, ttype::STRING) => out.arrow_schema = Some(r.read_binary()?),
                (_, ft) => r.skip(ft)?,
            }
        }
        Ok(out)
    }
}

pub struct FetchResultsResp {
    pub status: Status,
    pub has_more_rows: bool,
    pub results: Option<RowSet>,
    pub result_set_metadata: Option<ResultSetMetadata>,
}

impl FetchResultsResp {
    fn read(r: &mut Reader) -> TResult<Self> {
        let mut status = None;
        let mut has_more_rows = false;
        let mut results = None;
        let mut result_set_metadata = None;
        loop {
            let (ft, id) = r.read_field_begin()?;
            if ft == ttype::STOP {
                break;
            }
            match (id, ft) {
                (1, ttype::STRUCT) => status = Some(Status::read(r)?),
                (2, ttype::BOOL) => has_more_rows = r.read_bool()?,
                (3, ttype::STRUCT) => results = Some(RowSet::read(r)?),
                (1281, ttype::STRUCT) => result_set_metadata = Some(ResultSetMetadata::read(r)?),
                (_, ft) => r.skip(ft)?,
            }
        }
        Ok(Self {
            status: status.ok_or_else(|| ThriftError("TFetchResultsResp missing status".into()))?,
            has_more_rows,
            results,
            result_set_metadata,
        })
    }
}

pub struct OperationStatusResp {
    pub status: Status,
    pub operation_state: Option<i32>,
    pub error_message: Option<String>,
    pub display_message: Option<String>,
}

impl OperationStatusResp {
    fn read(r: &mut Reader) -> TResult<Self> {
        let mut status = None;
        let mut operation_state = None;
        let mut error_message = None;
        let mut display_message = None;
        loop {
            let (ft, id) = r.read_field_begin()?;
            if ft == ttype::STOP {
                break;
            }
            match (id, ft) {
                (1, ttype::STRUCT) => status = Some(Status::read(r)?),
                (2, ttype::I32) => operation_state = Some(r.read_i32()?),
                (5, ttype::STRING) => error_message = Some(r.read_string()?),
                // Field 1281, not 12 -- found while building the Thrift
                // mock test infra (this session) by cross-checking against
                // `databricks-sql-connector`'s own real, installed,
                // Apache-Thrift-compiler-generated `ttypes.py`: its
                // `TGetOperationStatusResp.thrift_spec` has no field 12 at
                // all; `displayMessage` is field 1281. Before this fix, a
                // real server's `GetOperationStatus.displayMessage` was
                // silently skipped by the `(_, ft) => r.skip(ft)?` catch-all
                // below (an unrecognized field id, not an error) --
                // `terminal_error()` still worked correctly in practice
                // because it checks the *top-level* `Status.display_message`
                // (field 6 of `TStatus`, correctly mapped, see `Status::read`
                // above) before ever falling back to this
                // operation-state-specific one, so this was a real but
                // narrow, never-observed-in-practice bug, not a regression
                // in any existing test or real-workspace verification.
                (1281, ttype::STRING) => display_message = Some(r.read_string()?),
                (_, ft) => r.skip(ft)?,
            }
        }
        Ok(Self {
            status: status.ok_or_else(|| ThriftError("TGetOperationStatusResp missing status".into()))?,
            operation_state,
            error_message,
            display_message,
        })
    }

    /// Terminal-with-error states (`ERROR`/`CANCELED`/`CLOSED`/`TIMEDOUT`)
    /// surface a message; `None` means either still running/pending, or
    /// cleanly `FINISHED`.
    pub fn terminal_error(&self) -> Option<String> {
        if let Some(e) = self.status.error() {
            return Some(e);
        }
        match self.operation_state {
            Some(operation_state::ERROR) => Some(
                self.display_message
                    .clone()
                    .or_else(|| self.error_message.clone())
                    .unwrap_or_else(|| "Thrift statement failed".to_string()),
            ),
            Some(operation_state::CANCELED) => Some("Thrift statement was canceled".to_string()),
            Some(operation_state::CLOSED) => Some("Thrift statement was closed server-side".to_string()),
            Some(operation_state::TIMEDOUT) => Some("Thrift statement timed out server-side".to_string()),
            _ => None,
        }
    }

    pub fn is_finished(&self) -> bool {
        self.operation_state == Some(operation_state::FINISHED)
    }
}

pub struct DirectResults {
    pub operation_status: Option<OperationStatusResp>,
    pub result_set_metadata: Option<ResultSetMetadata>,
    pub result_set: Option<FetchResultsResp>,
    pub already_closed: bool,
}

impl DirectResults {
    fn read(r: &mut Reader) -> TResult<Self> {
        let mut operation_status = None;
        let mut result_set_metadata = None;
        let mut result_set = None;
        let mut already_closed = false;
        loop {
            let (ft, id) = r.read_field_begin()?;
            if ft == ttype::STOP {
                break;
            }
            match (id, ft) {
                (1, ttype::STRUCT) => operation_status = Some(OperationStatusResp::read(r)?),
                (2, ttype::STRUCT) => result_set_metadata = Some(ResultSetMetadata::read(r)?),
                (3, ttype::STRUCT) => result_set = Some(FetchResultsResp::read(r)?),
                (4, ttype::STRUCT) => {
                    // TCloseOperationResp -- just a status; presence alone
                    // means the server already closed the operation for us.
                    already_closed = true;
                    r.skip(ttype::STRUCT)?;
                }
                (_, ft) => r.skip(ft)?,
            }
        }
        Ok(Self {
            operation_status,
            result_set_metadata,
            result_set,
            already_closed,
        })
    }
}

pub struct ExecuteStatementResp {
    pub status: Status,
    pub operation_handle: Option<OperationHandle>,
    pub direct_results: Option<DirectResults>,
}

impl ExecuteStatementResp {
    fn read(r: &mut Reader) -> TResult<Self> {
        let mut status = None;
        let mut operation_handle = None;
        let mut direct_results = None;
        loop {
            let (ft, id) = r.read_field_begin()?;
            if ft == ttype::STOP {
                break;
            }
            match (id, ft) {
                (1, ttype::STRUCT) => status = Some(Status::read(r)?),
                (2, ttype::STRUCT) => operation_handle = Some(OperationHandle::read(r)?),
                (1281, ttype::STRUCT) => direct_results = Some(DirectResults::read(r)?),
                (_, ft) => r.skip(ft)?,
            }
        }
        Ok(Self {
            status: status.ok_or_else(|| ThriftError("TExecuteStatementResp missing status".into()))?,
            operation_handle,
            direct_results,
        })
    }
}

// ---- The 7 RPC message pairs this crate needs ----------------------------

/// Builds one full Thrift RPC call message: `writeMessageBegin(method, CALL,
/// seqid)` + an "args" struct with the request at field 1 (matching every
/// generated `<Method>_args` struct in `TCLIService.py` -- always exactly
/// one field, `req`, at id 1) + field-stop. `seqid` is always 0 -- this
/// crate makes one synchronous call at a time per HTTP request/response
/// pair (no multiplexing over one transport the way a persistent Thrift
/// socket connection might), so distinguishing concurrent in-flight calls
/// by sequence id is never needed; matches `databricks-sql-connector`'s own
/// `self._seqid` which is likewise never incremented in the Databricks
/// Thrift-over-HTTP client.
fn build_call(method: &str, write_req: impl FnOnce(&mut Writer)) -> Vec<u8> {
    let mut w = Writer::new();
    w.write_message_begin(method, MESSAGE_TYPE_CALL, 0);
    w.write_field_begin(ttype::STRUCT, 1);
    write_req(&mut w);
    w.write_field_stop();
    w.into_bytes()
}

/// Parses one full Thrift RPC reply message: `readMessageBegin` (raising on
/// `EXCEPTION`), then the "result" struct, which always carries the actual
/// response at field id 0 (`success`, matching every generated
/// `<Method>_result` struct).
fn parse_reply<T>(bytes: &[u8], read_success: impl FnOnce(&mut Reader) -> TResult<T>) -> TResult<T> {
    let mut r = Reader::new(bytes);
    let (_name, msg_type, _seqid) = r.read_message_begin()?;
    if msg_type == MESSAGE_TYPE_EXCEPTION {
        return Err(ThriftError(read_application_exception(&mut r)?));
    }
    let mut read_success = Some(read_success);
    let mut result = None;
    loop {
        let (ft, id) = r.read_field_begin()?;
        if ft == ttype::STOP {
            break;
        }
        if id == 0 && ft == ttype::STRUCT {
            // `take()` is just satisfying the borrow checker for an `FnOnce`
            // inside a loop that only ever calls it once in practice.
            let f = read_success
                .take()
                .ok_or_else(|| ThriftError("duplicate `success` field in thrift reply".to_string()))?;
            result = Some(f(&mut r)?);
        } else {
            r.skip(ft)?;
        }
    }
    result.ok_or_else(|| ThriftError("thrift reply had no `success` field".to_string()))
}

pub fn build_open_session(req: &OpenSessionReq) -> Vec<u8> {
    build_call("OpenSession", |w| req.write(w))
}
pub fn parse_open_session(bytes: &[u8]) -> TResult<OpenSessionResp> {
    parse_reply(bytes, OpenSessionResp::read)
}

pub fn build_execute_statement(req: &ExecuteStatementReq) -> Vec<u8> {
    build_call("ExecuteStatement", |w| req.write(w))
}
pub fn parse_execute_statement(bytes: &[u8]) -> TResult<ExecuteStatementResp> {
    parse_reply(bytes, ExecuteStatementResp::read)
}

pub fn build_get_operation_status(op: &OperationHandle) -> Vec<u8> {
    build_call("GetOperationStatus", |w| {
        w.write_field_begin(ttype::STRUCT, 1);
        op.write(w);
        w.write_field_begin(ttype::BOOL, 2); // getProgressUpdate
        w.write_bool(false);
        w.write_field_stop();
    })
}
pub fn parse_get_operation_status(bytes: &[u8]) -> TResult<OperationStatusResp> {
    parse_reply(bytes, OperationStatusResp::read)
}

pub fn build_fetch_results(op: &OperationHandle, max_rows: i64, max_bytes: i64) -> Vec<u8> {
    build_call("FetchResults", |w| {
        w.write_field_begin(ttype::STRUCT, 1);
        op.write(w);
        w.write_field_begin(ttype::I32, 2); // orientation = FETCH_NEXT
        w.write_i32(0);
        w.write_field_begin(ttype::I64, 3);
        w.write_i64(max_rows);
        w.write_field_begin(ttype::I16, 4); // fetchType = 0 (query results, not logs)
        w.write_i16(0);
        w.write_field_begin(ttype::I64, 1281);
        w.write_i64(max_bytes);
        w.write_field_begin(ttype::BOOL, 1283); // includeResultSetMetadata
        w.write_bool(true);
        w.write_field_stop();
    })
}
pub fn parse_fetch_results(bytes: &[u8]) -> TResult<FetchResultsResp> {
    parse_reply(bytes, FetchResultsResp::read)
}

/// Shared shape for the three RPCs below: a single field-1 STRUCT handle,
/// nothing else in the request body.
fn build_handle_call(method: &str, write_handle: impl FnOnce(&mut Writer)) -> Vec<u8> {
    build_call(method, |w| {
        w.write_field_begin(ttype::STRUCT, 1);
        write_handle(w);
        w.write_field_stop();
    })
}

pub fn build_close_operation(op: &OperationHandle) -> Vec<u8> {
    build_handle_call("CloseOperation", |w| op.write(w))
}
pub fn parse_close_operation(bytes: &[u8]) -> TResult<Status> {
    parse_reply(bytes, Status::read)
}

pub fn build_cancel_operation(op: &OperationHandle) -> Vec<u8> {
    build_handle_call("CancelOperation", |w| op.write(w))
}
pub fn parse_cancel_operation(bytes: &[u8]) -> TResult<Status> {
    parse_reply(bytes, Status::read)
}

pub fn build_close_session(session: &SessionHandle) -> Vec<u8> {
    build_handle_call("CloseSession", |w| session.write(w))
}
pub fn parse_close_session(bytes: &[u8]) -> TResult<Status> {
    parse_reply(bytes, Status::read)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Round-trips a small struct (mirrors `TNamespace`) through the
    /// writer/reader to prove the primitive framing (field headers,
    /// strings, field-stop) matches between them -- the two are never
    /// otherwise exercised against each other directly (writer only ever
    /// talks to a real Databricks server, reader only ever parses real
    /// server responses), so this is the only place a systematic
    /// writer/reader mismatch (e.g. field id off by one) would show up
    /// without a real workspace.
    #[test]
    fn writer_reader_round_trip_namespace_shaped_struct() {
        let mut w = Writer::new();
        Namespace {
            catalog_name: Some("bms_dna"),
            schema_name: Some("core"),
        }
        .write(&mut w);
        let bytes = w.into_bytes();

        let mut r = Reader::new(&bytes);
        let (ft1, id1) = r.read_field_begin().unwrap();
        assert_eq!((ft1, id1), (ttype::STRING, 1));
        assert_eq!(r.read_string().unwrap(), "bms_dna");
        let (ft2, id2) = r.read_field_begin().unwrap();
        assert_eq!((ft2, id2), (ttype::STRING, 2));
        assert_eq!(r.read_string().unwrap(), "core");
        let (stop_ft, _) = r.read_field_begin().unwrap();
        assert_eq!(stop_ft, ttype::STOP);
    }

    #[test]
    fn message_begin_round_trips_strict_framing() {
        let mut w = Writer::new();
        w.write_message_begin("ExecuteStatement", MESSAGE_TYPE_CALL, 0);
        let bytes = w.into_bytes();
        let mut r = Reader::new(&bytes);
        let (name, mtype, seqid) = r.read_message_begin().unwrap();
        assert_eq!(name, "ExecuteStatement");
        assert_eq!(mtype, MESSAGE_TYPE_CALL);
        assert_eq!(seqid, 0);
    }

    /// Regression test for a real risk in a hand-rolled recursive-descent
    /// skip: an unbounded/garbage list size (e.g. from a corrupted or
    /// truncated response) must not panic via an out-of-bounds slice --
    /// `Reader::take` already checks bounds itself, this proves `skip`
    /// propagates that as a normal `Err` instead of panicking.
    #[test]
    fn skip_on_truncated_input_errors_instead_of_panicking() {
        // Claims 100 elements but the element-type byte and all data are
        // missing -- read_list_begin hits end-of-buffer trying to read past
        // what's given.
        let mut r = Reader::new(&[ttype::LIST as u8, 0, 0, 0, 100]);
        let err = r.skip(ttype::LIST);
        assert!(err.is_err(), "must error, not panic, on truncated/garbage input");
    }

    #[test]
    fn status_error_is_none_for_success_codes() {
        let ok = Status {
            status_code: status_code::SUCCESS,
            error_message: None,
            display_message: None,
        };
        assert!(ok.error().is_none());
        let ok_info = Status {
            status_code: status_code::SUCCESS_WITH_INFO,
            error_message: None,
            display_message: None,
        };
        assert!(ok_info.error().is_none());
    }

    #[test]
    fn status_error_prefers_display_message_over_error_message() {
        let bad = Status {
            status_code: status_code::ERROR,
            error_message: Some("raw error".to_string()),
            display_message: Some("pretty error".to_string()),
        };
        assert_eq!(bad.error().as_deref(), Some("pretty error"));
    }

    #[test]
    fn parameters_from_json_converts_sea_shaped_params() {
        let json = serde_json::json!([
            {"name": "a", "value": "5", "type": "INT"},
            {"name": "b", "value": 3.5, "type": "DOUBLE"},
        ]);
        let params = parameters_from_json(&json);
        assert_eq!(params.len(), 2);
        assert_eq!(params[0].name, "a");
        assert_eq!(params[0].value.as_deref(), Some("5"));
        assert_eq!(params[0].sql_type.as_deref(), Some("INT"));
        assert_eq!(params[1].value.as_deref(), Some("3.5"));
    }

    /// Regression test for the field-id fix on `(1281, ttype::STRING)` above
    /// -- see that arm's own comment for the full story.
    #[test]
    fn operation_status_resp_reads_display_message_from_field_1281_not_12() {
        let mut w = Writer::new();
        w.write_field_begin(ttype::STRUCT, 1);
        w.write_field_begin(ttype::I32, 1);
        w.write_i32(status_code::SUCCESS);
        w.write_field_stop();
        w.write_field_begin(ttype::I32, 2);
        w.write_i32(operation_state::FINISHED);
        w.write_field_begin(ttype::STRING, 1281);
        w.write_string("real display message");
        w.write_field_stop();
        let bytes = w.into_bytes();

        let mut r = Reader::new(&bytes);
        let resp = OperationStatusResp::read(&mut r).unwrap();
        assert_eq!(resp.display_message.as_deref(), Some("real display message"));
    }
}
